version: "3.8"

services:
  npm:
    image: docker.io/jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    volumes:
      - ./data/npm:/data
      - ./letsencrypt:/etc/letsencrypt
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    env_file: ./.env
    environment:
      - DISABLE_IPV6=true
    ports:
      - 80:80 # HTTP Expose
      - 81:81 # NPM GUI
      - 443:443 # HTTPS Expose
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
  torrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
      - ./data/qbittorrent/config:/config
      - "D:\\Media:/mnt/media"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    env_file: ./.env
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    # network_mode: host
    ports:
      - 8080:8080 # WebUI Port
      - 6881:6881 # Torrent
      - 6881:6881/udp # Torrent UDP
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex-media
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./data/plex/config:/config
      - ./data/plex/profiles:/config/profiles
      - "D:\\Media:/mnt/media"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    env_file: ./.env
    # network_mode: host
    ports:
      - 32400:32400 # Web UI
      - 1900:1900/udp
      - 3005:3005
      # - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-media
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
      - ./data/sonarr/config:/config
      - "D:\\Media:/mnt/media"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    env_file: ./.env
    # network_mode: host
    ports:
      - 8989:8989 # Web UI
    restart: unless-stopped
    depends_on:
      - torrent
      - jackett
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-media
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
      - ./data/radarr/config:/config
      - "D:\\Media:/mnt/media"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    env_file: ./.env
    # network_mode: host
    ports:
      - 7878:7878 # Web UI
    restart: unless-stopped
    depends_on:
      - torrent
      - jackett
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr-media
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
      - ./data/overseerr/config:/config
      - "D:\\Media:/mnt/media"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    env_file: ./.env
    environment:
      - PORT=5055
    # network_mode: host
    ports:
      - 5055:5055 # Web UI
    restart: unless-stopped
    depends_on:
      - torrent
      - jackett
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli-media
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
      - ./data/tautulli/config:/config
      - "D:\\Media:/mnt/media"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    env_file: ./.env
    # network_mode: host
    ports:
      - 8181:8181 # Web UI
    restart: unless-stopped
    depends_on:
      - torrent
      - jackett
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett-index
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
      - ./data/jackett/config:/config
      - "D:\\Media:/mnt/media"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    env_file: ./.env
    # network_mode: host
    ports:
      - 9117:9117 # Web UI
    restart: unless-stopped

networks:
  default:
    external: true
    name: nas
