version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    env_file: ./.env
    environment:
      - TZ=Asia/Samarkand
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    ports:
      - 8000:8000 # Reverse-tunneling
      - 9000:9000 # Portainer UI
      - 9443:9443 # Portainer UI (SSL)
    networks:
      - nas-connect
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  adghome:
    image: adguard/adguardhome:latest
    container_name: adghome
    volumes:
      - ./data/adghome/workdir:/opt/adguardhome/work
      - ./data/adghome/confdir:/opt/adguardhome/conf
    env_file: ./.env
    environment:
      - TZ=Asia/Samarkand
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    ports:
      - 53:53/tcp # plain DNS
      - 53:53/udp # plain DNS
      - 67:67/udp # DHCP server
      # - 68:68/udp # DHCP server
      - 80:80/tcp # Admin panel UI
      - 443:443/tcp # Admin panel UI (SSL)
      - 443:443/udp # Admin panel UI (SSL)
      - 3000:3000/tcp # Admin panel UI (SSL) OR DNS-over-HTTPS server
      - 853:853/tcp # DNS-over-TLS server
      - 784:784/udp # DNS-over-QUIC server
      - 853:853/udp # DNS-over-QUIC server
      - 8853:8853/udp # DNS-over-QUIC server
      - 5443:5443/tcp # DNSCrypt server
      - 5443:5443/udp # DNSCrypt server
    network_mode: host
    restart: unless-stopped
  speedtest:
    image: lscr.io/openspeedtest/latest:latest
    container_name: openspeedtest
    env_file: ./.env
    environment:
      - TZ=Asia/Samarkand
    ports:
      - 8100:3000
    network_mode: host
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  homebridge:
    image: lscr.io/oznu/homebridge:latest
    container_name: homebridge
    volumes:
      - ./data/homebridge:/homebridge
    env_file: ./.env
    environment:
      - TZ=Asia/Samarkand
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    ports:
      - 8581:8581 # Homebridge UI
      - 5353:5353/udp # mDNS lookup
    networks:
      - nas-connect
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  torrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
      - ./data/qbittorrent/config:/config
      - ./data/shared/downloads:/downloads
    env_file: ./.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Samarkand
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    network_mode: host
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex-media
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
      - ./data/plex/config:/config
      - ./data/plex/profiles:/config/profiles
      - ./data/shared/downloads:/downloads
    env_file: ./.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Samarkand
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      # - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    network_mode: host
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-media
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
      - ./data/sonarr/config:/config
      - ./data/shared/serials:/tv
      - ./data/shared/downloads:/downloads
    env_file: ./.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Samarkand
      - AUTO_UPDATE=false
    ports:
      - 8989:8989
    network_mode: host
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-media
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
      - ./data/radarr/config:/config
      - ./data/shared/movies:/movies
      - ./data/shared/downloads:/downloads
    env_file: ./.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Samarkand
      - AUTO_UPDATE=false
    ports:
      - 7878:7878
    network_mode: host
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
      - ./data/jackett/config:/config
      - ./data/shared/downloads:/downloads
    env_file: ./.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Samarkand
      - AUTO_UPDATE=false
    ports:
      - 9117:9117
    network_mode: host
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale-tunnel
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    env_file: ./.env
    environment:
      - TZ=Asia/Samarkand
    network_mode: host
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  s3:
    image: lscr.io/scality/s3server:latest
    container_name: s3-server
    env_file: ./.env
    environment:
      - TZ=Asia/Samarkand
    network_mode: host
    restart: unless-stopped

networks:
  nas-connect:
    driver: bridge
