version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    env_file: ./.env
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    ports:
      - 9443:9443
    network_mode: host
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  adghome:
    image: adguard/adguardhome:latest
    container_name: adghome
    volumes:
      - ./data/adghome/workdir:/opt/adguardhome/work
      - ./data/adghome/confdir:/opt/adguardhome/conf
    env_file: ./.env
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    ports:
      - 53:53/tcp # plain DNS
      - 53:53/udp # plain DNS
      - 67:67/udp # DHCP server
      - 68:68/udp # DHCP server
      - 80:80/tcp # Admin panel UI
      - 443:443/tcp # Admin panel UI (SSL)
      - 443:443/udp # Admin panel UI (SSL)
      - 3000:3000/tcp # DNS-over-HTTPS server
      - 853:853/tcp # DNS-over-TLS server
      - 784:784/udp # DNS-over-QUIC server
      - 853:853/udp # DNS-over-QUIC server
      - 8853:8853/udp # DNS-over-QUIC server
      - 5443:5443/tcp # DNSCrypt server
      - 5443:5443/udp # DNSCrypt server
    network_mode: host
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  speedtest:
    image: openspeedtest/latest:latest
    container_name: openspeedtest
    env_file: ./.env
    ports:
      - 8100:3000
    network_mode: host
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  torrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
      - ./data/qbittorrent/config:/config
      - ./data/shared/downloads:/downloads
    env_file: ./.env
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8080:8080
    network_mode: host
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  plex:
    image: linuxserver/plex:latest
    container_name: plex-media
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
      - ./data/plex/config:/config
      - ./data/shared/downloads:/downloads
    env_file: ./.env
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      # - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    network_mode: host
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    volumes:
      - ./data/homebridge:/homebridge
    env_file: ./.env
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    network_mode: host
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  s3:
    image: scality/s3server:latest
    container_name: s3-server
    env_file: ./.env
    network_mode: host
    restart: unless-stopped
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale-tunnel
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    env_file: ./.env
    network_mode: host
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
