version: '3.4'

services:
  torrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
      - ./data/qbittorrent/config:/config
      - ./data/shared/movies:/media/movies
      - ./data/shared/serials:/media/serials
      - ./data/shared/downloads:/media/downloads
    env_file: ./.env
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    network_mode: host
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex-media
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./data/plex/config:/config
      - ./data/plex/profiles:/config/profiles
      - ./data/shared/movies:/media/movies
      - ./data/shared/serials:/media/serials
      - ./data/shared/downloads:/media/downloads
    env_file: ./.env
    network_mode: host
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-media
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
      - ./data/sonarr/config:/config
      - ./data/shared/movies:/media/movies
      - ./data/shared/serials:/media/serials
      - ./data/shared/downloads:/media/downloads
    env_file: ./.env
    network_mode: host
    restart: unless-stopped
    depends_on:
      - torrent
      - jackett
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-media
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
      - ./data/radarr/config:/config
      - ./data/shared/movies:/media/movies
      - ./data/shared/serials:/media/serials
      - ./data/shared/downloads:/media/downloads
    env_file: ./.env
    network_mode: host
    restart: unless-stopped
    depends_on:
      - torrent
      - jackett
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr-media
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
      - ./data/overseerr/config:/config
      - ./data/shared/movies:/media/movies
      - ./data/shared/serials:/media/serials
      - ./data/shared/downloads:/media/downloads
    env_file: ./.env
    environment:
      - PORT=5055
    network_mode: host
    restart: unless-stopped
    depends_on:
      - torrent
      - jackett
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli-media
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
      - ./data/tautulli/config:/config
      - ./data/shared/movies:/media/movies
      - ./data/shared/serials:/media/serials
      - ./data/shared/downloads:/media/downloads
    env_file: ./.env
    ports:
      - 8181:8181
    network_mode: host
    restart: unless-stopped
    depends_on:
      - torrent
      - jackett
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett-index
    # devices:
    # - /dev/dri:/dev/dri
    volumes:
      - ./data/jackett/config:/config
      - ./data/shared/movies:/media/movies
      - ./data/shared/serials:/media/serials
      - ./data/shared/downloads:/media/downloads
    env_file: ./.env
    network_mode: host
    restart: unless-stopped
